In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame([12,34,78], columns=['Values'])
print(df)

   Values
0      12
1      34
2      78

In [26]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [27]:
data = {
    'Name' : ['Omer', 'Yousuf', 'Hannan' , 'Ámmar'],
    'Age' : [25, 30, 35, 40],
    'Salary' : [50000, 60000, 70000, 80000],
}

In [28]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0    Omer   25   50000
1  Yousuf   30   60000
2  Hannan   35   70000
3   Ámmar   40   80000

In [29]:
df.head(2)

     Name  Age  Salary
0    Omer   25   50000
1  Yousuf   30   60000

In [30]:
df.tail(3)
df.shape

(4, 3)

In [31]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [32]:
df.rename(columns={'Name': 'Full_Name'})

  Full_Name  Age  Salary
0      Omer   25   50000
1    Yousuf   30   60000
2    Hannan   35   70000
3     Ámmar   40   80000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [34]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

In [35]:
df.to_csv('omerpandas.csv')

In [36]:
load_df = pd.read_csv('omerpandas.csv')
load_df

   Unnamed: 0    Name  Age  Salary
0           0    Omer   25   50000
1           1  Yousuf   30   60000
2           2  Hannan   35   70000
3           3   Ámmar   40   80000

In [37]:
df[['Name', 'Age']]

     Name  Age
0    Omer   25
1  Yousuf   30
2  Hannan   35
3   Ámmar   40

In [38]:
df.loc[df.Name == 'Omer']

   Name  Age  Salary
0  Omer   25   50000

In [47]:
df.iloc[0:3]

     Name  Age  Salary
0    Omer   25   50000
1  Yousuf   30   60000
2  Hannan   35   70000

In [43]:
df[df['Age'] > 25]

     Name  Age  Salary
1  Yousuf   30   60000
2  Hannan   35   70000
3   Ámmar   40   80000

In [48]:
df.loc[0:3]

     Name  Age  Salary
0    Omer   25   50000
1  Yousuf   30   60000
2  Hannan   35   70000
3   Ámmar   40   80000